export const CONFIG = {
  organization: {
    name: "B-FLEXION",
    slug: "bflexion",
  },
  password: "12345678",
  counts: {
    owners: 1,
    admins: 5,
    members: 10,
    normalUsers: 50,
    locations: 50,
    events: 50,
    tags: 50,
    tagCategories: 5,
    areas: 10,
  },
} as const;

export const LONDON_AREAS = [
  "Soho",
  "Shoreditch",
  "Covent Garden",
  "Mayfair",
  "Chelsea",
  "Notting Hill",
  "Camden",
  "Brixton",
  "Fitzrovia",
  "Clerkenwell",
] as const;

export const TAG_DATA: Record<string, string[]> = {
  cuisine: [
    "Italian",
    "Japanese",
    "French",
    "Mexican",
    "Indian",
    "Thai",
    "Chinese",
    "Mediterranean",
    "British",
    "American",
    "Korean",
    "Vietnamese",
  ],
  ambiance: [
    "Cozy",
    "Romantic",
    "Lively",
    "Trendy",
    "Classic",
    "Modern",
    "Rustic",
    "Elegant",
    "Casual",
    "Industrial",
  ],
  features: [
    "Outdoor Seating",
    "Live Music",
    "Private Dining",
    "Rooftop",
    "Wine Bar",
    "Cocktail Bar",
    "Open Kitchen",
    "Chef's Table",
    "Tasting Menu",
    "Late Night",
  ],
  dietary: [
    "Vegetarian",
    "Vegan",
    "Gluten-Free",
    "Halal",
    "Kosher",
    "Organic",
    "Farm-to-Table",
    "Seafood",
  ],
  occasion: [
    "Date Night",
    "Business Dinner",
    "Birthday",
    "Anniversary",
    "Group Dining",
    "Solo Dining",
    "Brunch Spot",
    "Quick Bite",
  ],
};

export const TAG_CATEGORIES = [
  { name: "Cuisine", slug: "cuisine" },
  { name: "Ambiance", slug: "ambiance" },
  { name: "Features", slug: "features" },
  { name: "Dietary", slug: "dietary" },
  { name: "Occasion", slug: "occasion" },
] as const;
